spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stock
    username: root
    password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.demo.bean
server:
  port: 8080